apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
spec:
  version: 6.8.23
  count: 1
  elasticsearchRef:
    name: quickstart

  podTemplate:
    spec:
      automountServiceAccountToken: true
  http:
    tls:
      selfSignedCertificate:
        disabled: true
    service:
      spec:
        type: LoadBalancer
