version: '3'

services:
  es-node1:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.23
    container_name: es-node1
    environment:
      - node.name=node-1
      - discovery.zen.ping.unicast.hosts=es-node2,es-node3
      - discovery.zen.minimum_master_nodes=2
      - cluster.name=elasticsearch-cluster
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m -Des.enforce.bootstrap.checks=true -Des.security.authc.api_key.enabled=true"
      - ELASTIC_PASSWORD=changeme
      - "xpack.security.enabled=true"
      - "xpack.security.transport.ssl.enabled=true"
      - "xpack.security.transport.ssl.verification_mode=certificate"
      - "xpack.security.transport.ssl.keystore.path=/usr/share/elasticsearch/config/certificates/elastic-certificates.p12"
      - "xpack.security.transport.ssl.truststore.path=/usr/share/elasticsearch/config/certificates/elastic-certificates.p12"
      
    ports:
      - "9200:9200"
    volumes:
      - /c/Users/amsid/Documents/IntellijProjects/devtool/elasticsearch-kibana-docker-compose/es-node1/data:/usr/share/elasticsearch/data
      - /c/Users/amsid/Documents/IntellijProjects/devtool/elasticsearch-kibana-docker-compose/certificates:/usr/share/elasticsearch/config/certificates
    

  es-node2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.23
    container_name: es-node2
    environment:
      - node.name=node-2
      - discovery.zen.ping.unicast.hosts=es-node1,es-node3
      - discovery.zen.minimum_master_nodes=2
      - cluster.name=elasticsearch-cluster
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m -Des.enforce.bootstrap.checks=true -Des.security.authc.api_key.enabled=true"
      - ELASTIC_PASSWORD=changeme
      - "xpack.security.enabled=true"
      - "xpack.security.transport.ssl.enabled=true"
      - "xpack.security.transport.ssl.verification_mode=certificate"
      - "xpack.security.transport.ssl.keystore.path=/usr/share/elasticsearch/config/certificates/elastic-certificates.p12"
      - "xpack.security.transport.ssl.truststore.path=/usr/share/elasticsearch/config/certificates/elastic-certificates.p12"
      
    ports:
      - "9201:9200"
    volumes:
      - /c/Users/amsid/Documents/IntellijProjects/devtool/elasticsearch-kibana-docker-compose/es-node2/data:/usr/share/elasticsearch/data
      - /c/Users/amsid/Documents/IntellijProjects/devtool/elasticsearch-kibana-docker-compose/certificates:/usr/share/elasticsearch/config/certificates

  
  es-node3:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.23
    container_name: es-node3
    environment:
      - node.name=node-3
      - discovery.zen.ping.unicast.hosts=es-node1,es-node2
      - discovery.zen.minimum_master_nodes=2
      - cluster.name=elasticsearch-cluster
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m -Des.enforce.bootstrap.checks=true -Des.security.authc.api_key.enabled=true"
      - ELASTIC_PASSWORD=changeme
      - "xpack.security.enabled=true"
      - "xpack.security.transport.ssl.enabled=true"
      - "xpack.security.transport.ssl.verification_mode=certificate"
      - "xpack.security.transport.ssl.keystore.path=/usr/share/elasticsearch/config/certificates/elastic-certificates.p12"
      - "xpack.security.transport.ssl.truststore.path=/usr/share/elasticsearch/config/certificates/elastic-certificates.p12"
      
    ports:
      - "9202:9200"
    volumes:
      - /c/Users/amsid/Documents/IntellijProjects/devtool/elasticsearch-kibana-docker-compose/es-node3/data:/usr/share/elasticsearch/data
      - /c/Users/amsid/Documents/IntellijProjects/devtool/elasticsearch-kibana-docker-compose/certificates:/usr/share/elasticsearch/config/certificates

 