apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: logstash
  name: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - image: docker.elastic.co/logstash/logstash:7.8.0
          name: logstash
          ports:
            - containerPort: 25826
            - containerPort: 5044
          env:
            - name: ES_HOSTS
              value: "http://elasticsearch:9200"
            - name: TZ
              value: Asia/Kolkata
          resources: { }
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/logstash/config

            - name: logstash-pipeline-volume
              mountPath: /usr/share/logstash/pipeline
              readOnly: true

            - name: oraclelib
              mountPath: /usr/share/logstash/oraclelib

            - name: lastrunmetadata
              mountPath: /usr/share/logstash/lastrunmetadata

            - name: fileoutput
              mountPath: /usr/share/logstash/output
            - name: inputlogfilepath
              mountPath: /usr/share/logstash/input/logs

      restartPolicy: Always
      volumes:
        - name: config-volume
          configMap:
            name: logstash-configmap
            items:
              - key: logstash.yml
                path: logstash.yml

        - name: logstash-pipeline-volume
          configMap:
            name: logstash-configmap
            items:
              - key: logstash.conf
                path: logstash.conf
        - name: oraclelib
          hostPath:
            path:   /run/desktop/mnt/host/e/oraclelib

        - name: lastrunmetadata
          hostPath:
            path: /run/desktop/mnt/host/e/lastrunmetadata

        - name: fileoutput
          hostPath:
            path: /run/desktop/mnt/host/e/logstash/output

        - name: inputlogfilepath
          hostPath:
            path: /run/desktop/mnt/host/e/logstash/logfiles
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: logstash
  name: logstash
spec:
  ports:
    - name: "25826"
      port: 25826
      targetPort: 25826
    - name: "5044"
      port: 5044
      targetPort: 5044
  selector:
    app: logstash