apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-configmap
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
  logstash.conf: |
    # all input will come from filebeat, no local logs
    input {
      file {
        path => ["/usr/share/logstash/input/logs/*.log"]
        start_position 	=> "beginning"
      }
    }
    
    filter {
      json {
        source => "message"
      }
    }
    
    output {
      stdout {
        codec => json_lines
      }
      file {
        path => "/usr/share/logstash/output/output.txt"
        codec => json_lines
      }
      elasticsearch {
        action => "index"
        index => "currency-service-%{+YYYY.MM.dd}"
        document_type => "currency-service"
        hosts => [ "http://elasticsearch:9200" ]
      }
    }